/**
 * This file was auto-generated by the Titanium Module SDK helper for Android
 * Appcelerator Titanium Mobile
 * Copyright (c) 2009-2010 by Appcelerator, Inc. All Rights Reserved.
 * Licensed under the terms of the Apache Public License
 * Please see the LICENSE included with this distribution for details.
 *
 */
package de.appwerft.modbus;

import net.wimpi.modbus.procimg.SimpleDigitalIn;
import net.wimpi.modbus.procimg.SimpleDigitalOut;
import net.wimpi.modbus.procimg.SimpleInputRegister;
import net.wimpi.modbus.procimg.SimpleProcessImage;
import net.wimpi.modbus.procimg.SimpleRegister;

import org.appcelerator.kroll.KrollDict;
import org.appcelerator.kroll.KrollProxy;
import org.appcelerator.kroll.annotations.Kroll;

@Kroll.proxy(creatableInModule = ModbusModule.class)
public class SimpleProcessImageProxy extends KrollProxy {
	SimpleProcessImage spi;

	public SimpleProcessImageProxy() {
		spi = new SimpleProcessImage();
	}

	@Override
	public void handleCreationDict(KrollDict options) {
		super.handleCreationDict(options);

	}

	@Kroll.method
	public void addDigitalOut(boolean out) {
		spi.addDigitalOut(new SimpleDigitalOut(out));
	}

	@Kroll.method
	public void addDigitalInt(boolean in) {
		spi.addDigitalIn(new SimpleDigitalIn(in));
	}

	@Kroll.method
	public void addRegister(int in) {
		spi.addRegister(new SimpleRegister(in));
	}

	@Kroll.method
	public void addInputRegister(int in) {
		spi.addRegister(new SimpleInputRegister(in));
	}
}